- name:  Fix Web Server Start Service
  hosts: servera*
  gather_facts: false
  remote_user: devops
  tasks:
    # - name: Open Firewalld Port
    #   ansible.posix.firewalld:
    #     service: http
    #     immediate: true
    #     permanent: true
    #     state: enabled

    - name: Start web service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true
      become: true
