- name:  Deploy Missing Web Server Application
  hosts: servera*
  gather_facts: false
  remote_user: devops
  become: true
  tasks:
    # - name: Print Event As it is
    #   ansible.builtin.debug:
    #     msg: "{{ myevent }}"

    - name: Open Firewalld Port
      ansible.posix.firewalld:
        service: https
        immediate: true
        permanent: true
        state: enabled


    - name: Deploy Web App
      ansible.builtin.copy:
        content: "Hello DO274 Class"
        dest: /var/www/html/index.html


