---
- name: FTP server is installed
  hosts: all
  become: true
  gather_facts: true
  vars_files:
    - vars/defaults-template.yml
    - vars/vars.yml

  tasks:
    - name: Packages are installed
      vars:
        packages:
          - "{{ vsftpd_packages }}"
          - firewalld
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop: "{{ packages | flatten }}"

    - name: Start and enable services
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - "{{ vsftpd_service }}"
        - firewalld

    - name: Configuration file is installed
      ansible.builtin.template:
        src: templates/vsftpd.conf.j2
        dest: "{{ vsftpd_config_file }}"
        owner: root
        group: root
        mode: "0600"
        setype: etc_t
      notify: Restart vsftpd

    - name: Open ftp port in firewall
      ansible.posix.firewalld:
        service: ftp
        state: enabled
        permanent: true
        immediate: true

  handlers:
    - name: Restart vsftpd
      ansible.builtin.service:
        name: "{{ vsftpd_service }}"
        state: restarted
